# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='', max_length=50, verbose_name='\u8ba2\u5355\u53f7')),
                ('user_name', models.CharField(default='', max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
                ('tel', models.CharField(default='', max_length=50, verbose_name='\u7535\u8bdd')),
                ('add', models.CharField(default='', max_length=50, verbose_name='\u5730\u5740')),
                ('oil', models.CharField(default='', max_length=50, verbose_name='\u6cb9\u54c1')),
                ('liter', models.IntegerField(default=0, verbose_name='\u5347\u6570')),
                ('total_price', models.IntegerField(default=0, verbose_name='\u603b\u4ef7')),
                ('arrived_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6700\u665a\u9001\u8fbe\u65f6\u95f4')),
                ('remark', models.TextField(default='', verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8868\u5355',
                'verbose_name_plural': '\u8868\u5355',
            },
        ),
    ]
